# Generated by Django 4.2.7 on 2023-11-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bus_status_alter_location_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
