# Generated by Django 4.2.7 on 2023-11-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.FloatField(default=650),
            preserve_default=False,
        ),
    ]
