# Generated by Django 4.2.7 on 2023-11-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=51),
        ),
    ]
